name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Sync upstream
        run: |
          git remote add upstream https://github.com/Schnitze1/COS30049-Computing-Technology-Innovation-Project-2.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
